import { StyleSheet } from "react-native";

// Contains the shared visual styles for the expense tracker screen and its sections.
export const expenseTrackerStyles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: "#F4F1EA" },
  container: { width: "100%", maxWidth: 680, alignSelf: "center", padding: 24, paddingBottom: 48 },
  header: { flexDirection: "row", alignItems: "flex-start", justifyContent: "space-between", marginBottom: 28 },
  eyebrow: { color: "#7A5C3E", fontSize: 12, fontWeight: "800", letterSpacing: 1.5, marginBottom: 8 },
  title: { color: "#252A25", fontSize: 32, fontWeight: "800", letterSpacing: -0.5 },
  monthBadge: { backgroundColor: "#E5E0D5", borderRadius: 6, paddingHorizontal: 12, paddingVertical: 9 },
  monthBadgeText: { color: "#665C4C", fontSize: 11, fontWeight: "800", letterSpacing: 1 },
  totalCard: { backgroundColor: "#283D33", borderRadius: 10, padding: 24, marginBottom: 30 },
  totalLabel: { color: "#C6D5C9", fontSize: 11, fontWeight: "800", letterSpacing: 1.5 },
  totalAmount: { color: "#FFFDF8", fontSize: 44, fontWeight: "800", marginTop: 8 },
  totalCaption: { color: "#B5C6B9", fontSize: 14, marginTop: 5 },
  sectionHeader: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginBottom: 12 },
  sectionTitle: { color: "#252A25", fontSize: 18, fontWeight: "800" },
  sectionHint: { color: "#8C918B", fontSize: 13 },
  count: { color: "#7A5C3E", fontSize: 14, fontWeight: "800" },
  formCard: { backgroundColor: "#FFFDF8", borderColor: "#E4DED2", borderRadius: 10, borderWidth: 1, padding: 14, marginBottom: 30 },
  input: { color: "#252A25", fontSize: 16, paddingHorizontal: 8, paddingVertical: 10 },
  formRow: { flexDirection: "row", gap: 10, marginTop: 8 },
  amountInputWrap: { alignItems: "center", backgroundColor: "#F4F1EA", borderRadius: 6, flex: 1, flexDirection: "row", paddingHorizontal: 12 },
  currency: { color: "#665C4C", fontSize: 17, fontWeight: "700" },
  amountInput: { color: "#252A25", flex: 1, fontSize: 17, padding: 10 },
  addButton: { alignItems: "center", backgroundColor: "#B8653D", borderRadius: 6, justifyContent: "center", minHeight: 48, paddingHorizontal: 18 },
  addButtonText: { color: "#FFFDF8", fontSize: 14, fontWeight: "800" },
  expenseList: { backgroundColor: "#FFFDF8", borderColor: "#E4DED2", borderRadius: 10, borderWidth: 1, overflow: "hidden" },
  expenseRow: { alignItems: "center", borderBottomColor: "#EDE8DE", borderBottomWidth: 1, flexDirection: "row", minHeight: 76, paddingHorizontal: 14 },
  expenseIcon: { alignItems: "center", backgroundColor: "#E7EEE6", borderRadius: 20, height: 40, justifyContent: "center", width: 40 },
  expenseIconText: { color: "#42614B", fontSize: 17, fontWeight: "800" },
  expenseDetails: { flex: 1, marginLeft: 12 },
  expenseName: { color: "#252A25", fontSize: 15, fontWeight: "700" },
  expenseDate: { color: "#8C918B", fontSize: 12, marginTop: 4 },
  expenseAmount: { color: "#252A25", fontSize: 15, fontWeight: "800", marginRight: 12 },
  deleteButton: { alignItems: "center", height: 30, justifyContent: "center", width: 30 },
  deleteButtonText: { color: "#A09A8F", fontSize: 18, fontWeight: "500" },
  emptyState: { alignItems: "center", padding: 28 },
  emptyTitle: { color: "#252A25", fontSize: 15, fontWeight: "800" },
  emptyText: { color: "#8C918B", fontSize: 13, marginTop: 6 },
});